[env]
_.source = "./scripts/version-info.sh"

[tools]
go = "1.26.2"

[tasks.test]
run = "env"

[tasks.dev]
env = { "DEBUG" = 1 }
description = "Build and run dev version of workpls"
run = '''
go run -ldflags="-X github.com/Moorad/workpls/cmd.VERSION=dev -X github.com/Moorad/workpls/cmd.COMMIT=$COMMIT -X github.com/Moorad/workpls/cmd.DATE=$DATE" main.go
'''

[tasks.gen-cmd]
description = "Generates a command using cobra cli"
run = 'cobra-cli add'

[tasks.build]
description = "Build a production version of workpls"
usage = '''
arg "<version>" help="Application version"
'''
run = '''
go build -ldflags="-X github.com/Moorad/workpls/cmd.VERSION={{arg(name='version')}} -X github.com/Moorad/workpls/cmd.COMMIT=$COMMIT -X github.com/Moorad/workpls/cmd.DATE=$DATE" -o workpls .
'''

[tasks.deadcode]
description = "Find dead code in the codebase"
run = "go tool deadcode ./..."

